name: CI
'on':
  push:
    branches:
      - feature/**
      - fix/**
      - docs/**
      - master
      - dev
jobs:
  linting:
    strategy:
      matrix:
        node:
          - 12
          - 14
      fail-fast: true
    runs-on: ubuntu-latest
    name: Lint (node_${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - name: Install dependencies
        run: npm install
      - name: lint and format
        run: npm run fmt
      - name: Hadolint
        run: |
          docker run --rm -i hadolint/hadolint < ./srv/bitcoin/timelockBackend/Dockerfile
  tests:
    strategy:
      matrix:
        node:
          - 12
          - 14
      fail-fast: true
    runs-on: ubuntu-latest
    name: Test (node_${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - name: Install dependencies
        run: npm ci
      - name: Unittests
        run: npm run test
  build:
    strategy:
      matrix:
        node:
          - 12
          - 14
      fail-fast: true
    runs-on: ubuntu-latest
    name: Build (node_${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node }}'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
  docker:
    runs-on: ubuntu-latest
    name: Build docker
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm run docker:build
